#ifndef __SERVICE_REGISTRY_NOTIFIER_V01__
#define __SERVICE_REGISTRY_NOTIFIER_V01__

#include <stdint.h>
#include <limits.h>

typedef enum {
  QMI_SERVREG_NOTIF_SERVICE_STATE_ENUM_TYPE_MIN_ENUM_VAL_V01 = INT32_MIN,
  SERVREG_NOTIF_SERVICE_STATE_DOWN_V01 = 0x0FFFFFFF,
  SERVREG_NOTIF_SERVICE_STATE_UP_V01 = 0x1FFFFFFF,
  SERVREG_NOTIF_SERVICE_STATE_UNINIT_V01 = 0xFFFFFFFF,
  QMI_SERVREG_NOTIF_SERVICE_STATE_ENUM_TYPE_MAX_ENUM_VAL_V01 = INT32_MAX
} qmi_servreg_notif_service_state_enum_type_v01;
#endif /* __SERVICE_REGISTRY_NOTIFIER_V01__ */
